MVCClientVSFly/Models/Flight.cs
using System;

namespace MVCClientVSFly.Models
{
    public class Flight
    {
        public int FlightNo { get; set; }

        public string Departure { get; set; }

        public string Destination { get; set; }
        public DateTime Date { get; set; }

        public short? Seats { get; set; }
        public short AvailableSeats { get; set; }

        public double SeatPrice { get; set; }
    }
}

MVCClientVSFly/Controllers/BookingsController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace MVCClientVSFly.Controllers
{
    public class BookingsController : Controller
    {
        private static HttpClient _httpClient;
        // GET: FlightsController

        static BookingsController()
        {
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = new Uri("https://localhost:44349/");
        }


        // GET: BookingsController/Create
        public ActionResult Create(Models.Flight f)
        {
            Models.Booking b = new Models.Booking();

            b.FlightNo = f.FlightNo;
            b.Price = f.SeatPrice;

            return View(b);
        }

        

        // POST: BookingsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Models.Booking b)
        {
            Models.Message m = new Models.Message();
                string bookingJson = JsonConvert.SerializeObject(b);
                HttpContent stringContent = new StringContent(bookingJson, Encoding.UTF8, "application/json");
                HttpResponseMessage response = await _httpClient.PostAsync(("api/Bookings"), stringContent);
            try
            {
                response.EnsureSuccessStatusCode();
                
                m.Content = "Réservation effectué";

                return View("ShowMessage", m);
            }
            catch
            {
                m.Content = await response.Content.ReadAsStringAsync();
                return View("ShowMessage", m);
            }
        }


    }
       
}

MVCClientVSFly/Controllers/FlightController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace MVCClientVSFly.Controllers
{
    public class FlightController : Controller
    {
        private static HttpClient _httpClient;

        static FlightController()
        {
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = new Uri("https://localhost:44311/");
        }
        // GET: FlightController
        public async Task<ActionResult> IndexAsync()
        {
            HttpResponseMessage response = await _httpClient.GetAsync("api/Flights");
            response.EnsureSuccessStatusCode();
            string message = await response.Content.ReadAsStringAsync();

            IEnumerable<Models.Flight> listFlight = JsonConvert.DeserializeObject<IEnumerable<Models.Flight>>(message);

            return View(listFlight);
        }

        // GET: FlightController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: FlightController/Create
        public async Task<ActionResult> CreateAsync(Models.Flight f)
        {
            try
            {
                string flightJson = JsonConvert.SerializeObject(f);
                HttpContent stringContent = new StringContent(flightJson, Encoding.UTF8, "application/json");
                var response = await _httpClient.PostAsync("api/PostFlight", stringContent);
                response.EnsureSuccessStatusCode();

                var data = await response.Content.ReadAsStringAsync();
                Models.Message m = new Models.Message();
                m.Content = data;

                return View("ShowMessage");

                return RedirectToAction(nameof(IndexAsync));
            }
            catch
            {
                return View();
            }
        }

        // POST: FlightController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(IndexAsync));
            }
            catch
            {
                return View();
            }
        }

        // GET: FlightController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: FlightController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(IndexAsync));
            }
            catch
            {
                return View();
            }
        }

        // GET: FlightController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: FlightController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(IndexAsync));
            }
            catch
            {
                return View();
            }
        }
    }
}

MVCClientVSFly/Controllers/FlightsController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;

namespace MVCClientVSFly.Controllers
{
    public class FlightsController : Controller
    {
        private static HttpClient _httpClient;

        // GET: FlightsController
        static FlightsController()
        {
            _httpClient = new HttpClient();
            _httpClient.BaseAddress= new Uri("https://localhost:44349/");
        }

        public async Task<ActionResult> IndexAsync()
        {
            HttpResponseMessage response = await _httpClient.GetAsync("api/Flights");
            response.EnsureSuccessStatusCode();
            string message = await response.Content.ReadAsStringAsync();

            IEnumerable<Models.Flight> listFlight = JsonConvert.DeserializeObject<IEnumerable<Models.Flight>>(message);
            List<Models.Flight> listFlightM = new List<Models.Flight>();

            foreach (Models.Flight f in listFlight)
            {
                   listFlightM.Add(f);  
            }

            return View("IndexAsync", listFlightM);
        }
    }
}

MVCClientVSFly/Views/Flights/IndexAsync.cshtml
@model IEnumerable<MVCClientVSFly.Models.Flight>

@{
    ViewData["Title"] = "IndexAsync";
}

<h1>IndexAsync</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FlightNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Departure)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Destination)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AvailableSeats)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SeatPrice)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FlightNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Departure)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Destination)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AvailableSeats)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SeatPrice)
            </td>
            <td>
                @Html.ActionLink("Book", "Create", "Bookings", item)

            </td>
        </tr>
}
    </tbody>
</table>

MVCClientVSFly/Views/Flights/ShowMessage.cshtml
@model MVCClientVSFly.Models.Message

@{
    ViewData["Title"] = "ShowMessage";
}

<h1>ShowMessage</h1>

<div>
    <h4>Message</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>