MVCClientVSFly/Models/Booking.cs
namespace MVCClientVSFly.Models
{
    public class Booking
    {
        public int FlightNo { get; set; }
        public string Surname { get; set; }
        public string GivenName { get; set; }
        public int Weight { get; set; }
        public double Price { get; set; }
    }
}

MVCClientVSFly/Controllers/BookingsController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace MVCClientVSFly.Controllers
{
    public class BookingsController : Controller
    {
        private static HttpClient _httpClient;
        // GET: FlightsController

        static BookingsController()
        {
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = new Uri("https://localhost:44349/");
        }


        // GET: BookingsController/Create
        public ActionResult Create(Models.Flight f)
        {
            Models.Booking b = new Models.Booking();

            b.FlightNo = f.FlightNo;
            b.Price = f.SeatPrice;

            return View(b);
        }

        

        // POST: BookingsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Models.Booking b)
        {
            Models.Message m = new Models.Message();
                string bookingJson = JsonConvert.SerializeObject(b);
                HttpContent stringContent = new StringContent(bookingJson, Encoding.UTF8, "application/json");
                HttpResponseMessage response = await _httpClient.PostAsync(("api/Bookings"), stringContent);
            try
            {
                response.EnsureSuccessStatusCode();
                
                m.Content = "Réservation effectué";

                return View("ShowMessage", m);
            }
            catch
            {
                m.Content = await response.Content.ReadAsStringAsync();
                return View("ShowMessage", m);
            }
        }


    }
       
}

MVCClientVSFly/Controllers/FlightsController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;

namespace MVCClientVSFly.Controllers
{
    public class FlightsController : Controller
    {
        private static HttpClient _httpClient;

        // GET: FlightsController
        static FlightsController()
        {
            _httpClient = new HttpClient();
            _httpClient.BaseAddress= new Uri("https://localhost:44349/");
        }

        public async Task<ActionResult> IndexAsync()
        {
            HttpResponseMessage response = await _httpClient.GetAsync("api/Flights");
            response.EnsureSuccessStatusCode();
            string message = await response.Content.ReadAsStringAsync();

            IEnumerable<Models.Flight> listFlight = JsonConvert.DeserializeObject<IEnumerable<Models.Flight>>(message);
            List<Models.Flight> listFlightM = new List<Models.Flight>();

            foreach (Models.Flight f in listFlight)
            {
                   listFlightM.Add(f);  
            }

            return View("IndexAsync", listFlightM);
        }
    }
}

MVCClientVSFly/Views/Bookings/Create.cshtml
@model MVCClientVSFly.Models.Booking

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Booking</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FlightNo" class="control-label"></label>
                <input asp-for="FlightNo" class="form-control" disabled="disabled" />
                <input asp-for="FlightNo" type="hidden" name="FlightNo" />
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GivenName" class="control-label"></label>
                <input asp-for="GivenName" class="form-control" />
                <span asp-validation-for="GivenName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Weight" class="control-label"></label>
                <input asp-for="Weight" class="form-control" />
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" disabled="disabled" />
                <input asp-for="Price" type="hidden" name="Price" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCClientVSFly/Views/Bookings/ShowMessage.cshtml
@model MVCClientVSFly.Models.Message

@{
    ViewData["Title"] = "ShowMessage";
}

<h1>ShowMessage</h1>

<div>
    <h4>Message</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("To flights list","Index", "Flights")
</div>